name: lintorium

version: '312.0.0'

license: 'BSD-3-Clause'

description: "A set of strict lint rules for Dart. Unlike other packages, lintorium keeps the same ruleset configured identically across every supported Dart SDK version."

repository: https://github.com/ilexbor/lintorium

issue_tracker: https://github.com/ilexbor/lintorium/issues

environment:
  sdk: '>=3.12.0 <4.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - analysis-options
  - analyzer-diagnostics
  - code-style
  - linter-rules
  - lints